name: ci-golang-workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  check-app:
    runs-on: ubuntu-latest
    steps:
      # Go
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.24
      - run: go test

      # Docker
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and Push
        uses: docker/build-push-action@v6
        id: docker-build
        with:
          context: .
          push: true # false
          tags: lucasmdomingues/fullcycle-ci:latest
